name: Lint

on: push

jobs:
  linter:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Debian Dockerfile
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: "docker/debian/Dockerfile"

      - name: Lint CentOS Dockerfile
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile: "docker/centos/Dockerfile"
